insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Jaxspan', 'Mech compl of cardiac electrode, initial encounter', 'Incise bartholin''s gland');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Zoomzone', 'Superficial frostbite of right hip and thigh, init encntr', 'Revis cleft palat repair');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skipfire', 'Contact with other mammals', 'Imp bivn ext hrt ast sys');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Fliptune', 'Oth fx shaft of right ulna, init for opn fx type I/2', 'Renal anastomosis');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Kwilith', 'Pasngr in pk-up/van inj in clsn w 2/3-whl mv nontraf, sqla', 'Imp/repl brain stim lead');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Ntags', 'Laceration w/o foreign body of oth part of head, subs encntr', 'Open valvuloplasty NOS');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Trilith', 'Toxic effect of venom of ants, assault, subsequent encounter', 'Xtraoc mus op/detach NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skinder', 'Bursitis of unspecified shoulder', 'Plastic rep ext ear NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Realblab', 'Other derangements of patella', 'Excision of shoulder NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tazzy', 'Laceration without foreign body, right thigh, init encntr', 'Bronchoscopy thru stoma');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Eazzy', 'Personal history of (healed) nontraumatic fracture', 'Urethral repair NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Edgeblab', 'Sequelae of viral encephalitis', 'Cervical les cauterizat');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Flipbug', 'Disp fx of lateral epicondyl of r humer, 7thK', 'Excision eye lesion NOS');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Zoombox', 'Other specified disorders of bone', 'Contrast arthrogram');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Twiyo', 'Superficial frostbite of unspecified ear', 'Bladder exstrophy repair');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Gabtune', 'Laceration with foreign body of forearm', 'Lap res transverse colon');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Chatterpoint', 'Salter-Harris Type III physeal fracture of upper end radius', 'Male genital x-ray NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tazz', 'Burn of first deg mult fingers (nail), including thumb', 'Carporadial fusion');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Miboo', 'Unspecified subluxation of right wrist and hand, subs encntr', 'Transplant hand tend NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skinder', 'Salter-Harris Type I physeal fracture of r calcaneus, init', 'Cell blk/pap-op wound');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Eayo', 'Toxic effect of beryllium and its compounds, assault', 'Int/comb version no extr');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Zoovu', 'Disp fx of pisiform, right wrist, subs for fx w delay heal', 'Rep recur shlder disloc');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Quimba', 'Other specified injury of axillary artery, right side', 'Thomas'' splint traction');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Jabberstorm', 'Unspecified cholesteatoma', 'GI tract instillat NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Wordware', 'Minor laceration of right carotid artery, sequela', 'Open fx reduction NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Devcast', 'Nondisplaced fracture of first metatarsal bone, left foot', 'Lap dir ing hern-graft');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Mycat', 'Other specified conditions of integument specific to newborn', 'Stern lg bowel interpos');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Mynte', 'Radiohumeral (joint) sprain of unsp elbow, subs encntr', 'Perc extrac com duc calc');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Bluezoom', 'Furuncle of unspecified foot', 'Closed uterine biopsy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Twitternation', 'Unsp pedl cyclst injured in clsn w 2/3-whl mv in traf, subs', 'Biliary tr dx proc NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Jazzy', 'Inj femoral vein at hip and thigh level, unsp leg, init', 'Mandibular reconst NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Shuffletag', 'Other injury due to accident to watercraft', 'Opn mul seg lg intes NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Camimbo', 'Chronic angle-closure glaucoma, r eye, indeterminate stage', 'Abdominal tomography NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Rhyloo', 'Other specified injuries of larynx, sequela', 'Referral psych rehab NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Zava', 'Oth foreign object in pharynx causing asphyxiation, sequela', 'Eye evisc w synch implan');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Vipe', 'Adverse effect of propionic acid derivatives', 'Dermabrasion');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Photobean', 'Multiple defects of retina without detachment, left eye', 'Gas hysterosalpingogram');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Einti', 'Cognitive communication deficit', 'Debrid opn fx-radius/uln');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tavu', 'Oth superficial bite of right front wall of thorax, init', 'Eyebal/orbit dx proc NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Mudo', 'I/I react d/t indwelling urethral catheter, init', 'Xtraoc mus op/detach NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Camimbo', 'Bent bone of r rad, subs for opn fx type 3A/B/C w routn heal', 'Imp/rep schan coch pros');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tazzy', 'Other multiple births, all stillborn', 'Other pleural incision');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Viva', 'Disp fx of greater tuberosity of r humerus, init for opn fx', 'Ins left atr append dev');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Aimbo', 'Oth extrartic fx low end r rad, 7thR', 'Imp/rep CRT defib genat');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Feedfire', 'Pilonidal sinus without abscess', 'Repair of uvula');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Twinder', 'Mtrcy passenger injured in clsn w 2/3-whl mv nontraf, init', 'Repair ob lac corp uteri');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Ainyx', 'Lead-induced chronic gout, unspecified elbow', 'Small-to-large bowel NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skippad', 'Breakdown (mechanical) of ventricular intracranial shunt', 'Therapeut evac ant chamb');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Camido', 'Corrosion of larynx and trachea', 'Skull biopsy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Oyoyo', 'Cont preg aft elctv fetl rdct of 1 fts or more,3rd tri, fts2', 'Grft repair hrt sept NOS');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Omba', 'Occupant of stcar injured in clsn w mtr veh in traf, sequela', 'Lap gastric restric proc');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Buzzster', 'Disp fx of med phalanx of l lit fngr, 7thD', 'Remov intralum laryn FB');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Talane', 'Inj cutan sensory nerve at ank/ft level, left leg, subs', 'Other bone dx proc NOS');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Quinu', 'Passenger in hv veh injured in clsn w statnry object nontraf', 'Glaucoma testing');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Fiveclub', 'NB aff by abnlt in fetl hrt rate or rhythm, unsp time onset', 'Cervical lymphangiogram');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Jabberbean', 'Stable burst fx second thor vert, subs for fx w delay heal', 'Clubfoot release NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Zava', 'Malignant melanoma of left eyelid, including canthus', 'Cardiac stress test NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Avavee', 'Preterm labor without delivery, second trimester', 'Complete sialoadenectomy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Twiyo', 'Contusion of middle finger with damage to nail', 'Myringotomy NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Yodo', 'Unsp fracture of right forearm, subs for clos fx w nonunion', 'Part dacryoadenect NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Minyx', 'Nondisp fx of low epiphy (separation) of unsp femr, 7thC', 'Anterior chamber op NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Dabvine', 'Occup of 3-whl mv injured in collision w ped/anml nontraf', 'Vaginal suspens & fixat');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Gigazoom', 'Nontraumatic ischemic infarction of muscle, right shoulder', 'Lap unilat oophorectomy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Dynabox', 'Cerebral infrc to thrombosis of bilateral posterior arteries', 'Insert 1 vascular stent');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Mynte', 'Occup of bus injured in collision w 2/3-whl mv in traf, subs', 'Nasal lesion excis NOS');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Twiyo', 'Unspecified injury of superficial palmar arch', 'Incision of uvula');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Meembee', 'Inj cutan sensory nerve at ank/ft level, right leg, sequela', 'Sympathetic nerve biopsy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Aimbu', 'Disp fx of cuboid bone of r foot, subs for fx w routn heal', 'Rect/perirect dx op NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Yodo', 'Dissection of aorta', 'Op red-int fix metat/tar');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Roodel', 'Fall due to ice and snow', 'Insert 4+ vasculr stents');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Aimbo', 'Dislocation of distal interphaln joint of l mid finger, init', 'Suture ureteral lacerat');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('DabZ', 'Person injured in clsn betw car and 2/3-whl pwr veh, init', 'Teleradio using photons');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Devbug', 'Unsp fx lower end of r ulna, subs for clos fx w delay heal', 'Pharyngotomy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Jatri', 'Nondisp fx of olecran pro w/o intartic extn l ulna, 7thR', 'Endosc inser nasobil tub');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Browsetype', 'Auditory recruitment', 'Uterine les destruct NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skyble', 'Adverse effect of emetics, initial encounter', 'Coronary bld flow monit');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Babblestorm', 'Nondisplaced transverse fracture of shaft of right ulna', 'Endo emb hd/nk,bare coil');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Demizz', 'Oth fx of lower end r radius, subs for clos fx w delay heal', 'Hair transplant');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Trilith', 'Choroidal degeneration, unspecified, left eye', 'Pancreat cyst marsupiali');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Jabberstorm', 'Complete traumatic trnsphal amputation of right thumb, subs', 'Artif rupt membranes NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Abata', '39 weeks gestation of pregnancy', 'Bact smear-lower urinary');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Ntags', 'War op w explosn of improv explosv device, civilian, sequela', 'Pressurized treat graft');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skivee', 'Path fracture in neoplastic disease, unsp humerus, init', 'Electrocardiograph monit');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Talane', 'Other fracture of third metacarpal bone, right hand', 'Open red-int fix finger');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Katz', 'Athscl native arteries of extrm w rest pain, unsp extremity', 'Oth metac/carp rep/plast');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Skyndu', 'Displaced spiral fracture of shaft of right femur, init', 'Incision of chest wall');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Twitterlist', 'Corrosion of third degree of right scapular region, subs', 'Other therapeu apheresis');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Trilith', 'Maternal care for viable fetus in abd preg, third tri, unsp', 'Rad neck dissection NOS');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Wordtune', 'Tension-type headache, unspecified, intractable', 'Nephropexy');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Flipstorm', 'Superficial foreign body of toe', 'Bone graft to humerus');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Brightbean', 'Motorcycle driver injured in collision w 2/3-whl mv in traf', 'Other laryngeal repair');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Kaymbo', 'Unsp injury of ulnar artery at forarm lv, right arm, subs', 'Trigeminal nerv division');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tekfly', 'Burn unsp deg of shldr/up lmb, ex wrs/hnd, unsp site, subs', 'Lap total abdominal hyst');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Riffpath', 'Pathological fracture, left ankle, subs for fx w nonunion', 'Closed fx reduct humerus');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tanoodle', 'Unspecified open wound of unspecified elbow', 'Nasal repair NEC');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Ntags', 'Poisn by antimalari/drugs acting on bld protzoa, asslt, subs', 'Mmr administration');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Tagcat', 'Incomplete lesion of L4 level of lumbar spinal cord, subs', 'After catar fragmntation');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Brainlounge', 'Path fx in neopltc dis, unsp hand, subs for fx w malunion', 'Opn aortic valvuloplasty');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Topicware', 'Hallux varus (acquired)', 'Comb alcohol/drug detox');
insert into SupervisionGroups ( projectTitle, description,  KnowledgeArea) values ('Ooba', 'Nondisp fx of coronoid pro of unsp ulna, 7thQ', 'Loc exc les tibia/fibula');
