// <auto-generated />
namespace CollegeWebFormApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatestudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatestudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202002282219024_update student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
