// <auto-generated />
namespace CollegeWebFormApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202004060915426_addColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
